--A. Given the subset of DoneDeals schema below, write executable SQL queries to answer th--e following:

--1. Determine the number of active ads on the site per day (use generate_series).
--QUERY PREPARED AS BELOW

----COMMENTS
----"CREATE" COLUMN IN ADS TABLE IS USED AS "CREATED" TO AVOID KEYWORD CONFLICT
----"DELETE" COLUMN IN ADS TABLE IS USED AS "DELETED" TO AVOID KEYWORD CONFLICT
----ASSUMED IF "DELETED" COLUMN IS NULL THAT MEANS AD IS STILL ACTIVELY PUBLISHED
----"DELETED" DAY IS NOT COUNTED AS ACTIVE DATE FOR AN ADD

SELECT D.DAYZ AS ON_DATE, COUNT(M.ID) AS ACTIVE_ADS  
FROM 
-- TO GET MASTER DAYS SEQUENCE STARTING FROM LEAST CREATED DATE IN DB TILL CURRENT DB SYSTEM DATE 
(SELECT CAST(GENERATE_SERIES(MIN(CREATED),CURRENT_DATE,INTERVAL '1 DAY') AS DATE) AS DAYZ FROM ADS) D 
LEFT JOIN
-- TO GENERATE DAYS FOR EACH AD IN BETWEEN PUBLISHING DATE TILL DELETION DATE
(SELECT ID ,CAST(GENERATE_SERIES(PUBLISH,COALESCE(DELETED- INTERVAL '1 DAY',CURRENT_DATE),INTERVAL '1 DAY') AS DATE) AS DAYZ FROM ADS ORDER BY 2) M 
ON D.DAYZ = M.DAYZ
GROUP BY D.DAYZ
ORDER BY 1;



---2. Determine the YoY growth of Beef Cattle ads in county Tipperary from 2016 to 2017 (use lag).

---FORMULA FOR YOY GROWTH IS CONSIDERED AS (ADS IN 2017- ADS IN 2016)*100/(ADS IN 2016)
---ADS CREATED IN DB BUT NOT PUBLISHED IN WEB ARE NOT CONSIDERED IN THE QUERY


SELECT YR , NO_OF_ADS ,  YOY , YOY_PER FROM (
SELECT YR , NO_OF_ADS , NO_OF_ADS - LAG(NO_OF_ADS, 1) OVER ( ORDER BY YR) YOY , 
(NO_OF_ADS - LAG(NO_OF_ADS, 1) OVER ( ORDER BY YR))*100.00/(LAG(NO_OF_ADS, 1) OVER ( ORDER BY YR)) AS YOY_PER
FROM
(SELECT EXTRACT(YEAR FROM PUBLISH) YR, COUNT(A.ID) NO_OF_ADS
FROM ADS A, CATEGORY C, REGION R 
WHERE A.CATEGORY_ID = C.ID 
AND A.REGION_ID = R.ID
AND UPPER(C.SUBSUBCATEGORY) = 'BEEF CATTLE'
AND UPPER(R.COUNTY) = 'TIPPERARY'
AND A.PUBLISH IS NOT NULL
AND  EXTRACT(YEAR FROM PUBLISH) IN ('2016','2017')
GROUP BY EXTRACT(YEAR FROM PUBLISH))M
ORDER BY 1) Y
WHERE YR = '2017';